- name: Fellow
  label: An OpenNews fellow
  obj: entity
  hidden: no
  parent: 'Person'
  attributes:
    - name: twitter_handle
      label: Twitter handle

- name: NewsOrganization
  label: A news organization
  obj: entity
  hidden: no
  parent: 'Company'
  attributes:
    - name: url
      label: URL

- name: Fellowship
  label: A Fellowship
  label_in: Was hosted by
  label_out: Worked for
  obj: relation
  attributes: []
